In [64]:
# Importing the libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

# Ignoring the warnings

import warnings
warnings.filterwarnings("ignore")

import pandasql as psql

In [65]:
# Load the Boston housing data

InsClaims = pd.read_csv(r"D:\iiit notes\Programming\AI\Internship practice\45 season 20-jul-2021\insurance_claims.csv", header=0)
InsClaims.head()

months_as_customer  age  policy_number policy_bind_date policy_state  \
0                 328   48         521585       2014/10/17           OH   
1                 228   42         342868       2006/06/27           IN   
2                 134   29         687698       2000/09/06           OH   
3                 256   41         227811       1990/05/25           IL   
4                 228   44         367455       2014/06/06           IL   

  policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0    250/500               1000                1406.91               0   
1    250/500               2000                1197.22         5000000   
2    100/300               2000                1413.14         5000000   
3    250/500               2000                1415.74         6000000   
4   500/1000               1000                1583.91         6000000   

   insured_zip  ... police_report_available total_claim_amount injury_claim  \
0       466132  ...                     YES              71610         6510   
1       468176  ...                       ?               5070          780   
2       430632  ...                      NO              34650         7700   
3       608117  ...                      NO              63400         6340   
4       610706  ...                      NO               6500         1300   

  property_claim vehicle_claim  auto_make  auto_model auto_year  \
0          13020         52080       Saab         92x      2004   
1            780          3510   Mercedes        E400      2007   
2           3850         23100      Dodge         RAM      2007   
3           6340         50720  Chevrolet       Tahoe      2014   
4            650          4550     Accura         RSX      2009   

  fraud_reported _c39  
0              Y  NaN  
1              Y  NaN  
2              N  NaN  
3              Y  NaN  
4              N  NaN  

[5 rows x 40 columns]

In [66]:
# Delete the variable '_c39'

del InsClaims['_c39']

In [67]:
# Replace target variable 'police_report_available', 'Yes' to 1 , 'No' to 0 and '?' to 0 & convert values to integer.

InsClaims['fraud_reported'] = InsClaims['fraud_reported'].str.replace('Y', '1')
InsClaims['fraud_reported'] = InsClaims['fraud_reported'].str.replace('N', '0')
InsClaims['fraud_reported'] = InsClaims['fraud_reported'].astype(int)

In [68]:
# Display the max and min values of policy_annual_premium

print(InsClaims.policy_annual_premium.max())
print(InsClaims.policy_annual_premium.min())

2047.59
433.33


In [69]:
# Display the max and min values of months_as_customer

print(InsClaims.months_as_customer.max())
print(InsClaims.months_as_customer.min())



479
0


In [70]:
# Create a range for months_as_customer

InsClaims['Range-mac'] = pd.cut(x=InsClaims['months_as_customer'], bins=[-1, 20, 40, 60, 80, 100, 500],
labels=['0 to 20', '21 to 40', '41 to 60', '61 to 80', '81 to 100', '101 to 500'])

In [71]:
# Convert th 'policy_state' into integer value

InsClaims['policy_state'] = InsClaims['policy_state'].str.replace('OH', '1')
InsClaims['policy_state'] = InsClaims['policy_state'].str.replace('IN', '2')
InsClaims['policy_state'] = InsClaims['policy_state'].str.replace('IL', '3')
InsClaims['policy_state'] = InsClaims['policy_state'].astype(int)

In [72]:
# Convert th 'policy_state' into integer value

InsClaims['policy_csl'] = InsClaims['policy_csl'].str.replace('100/300', '1')
InsClaims['policy_csl'] = InsClaims['policy_csl'].str.replace('250/500', '2')
InsClaims['policy_csl'] = InsClaims['policy_csl'].str.replace('500/1000', '3')
InsClaims['policy_csl'] = InsClaims['policy_csl'].astype(int)

In [73]:
# Convert the 'insured_education_level' into interger

InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('High School', '1')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('College', '2')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('Associate', '3')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('JD', '3')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('Masters', '4')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('MD', '4')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].str.replace('PhD', '5')
InsClaims['insured_education_level'] = InsClaims['insured_education_level'].astype(int)

In [74]:
# Convert the 'insured_relationship' into integer

InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('own-child', '1')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('other-relative', '1')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('husband', '1')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('wife', '1')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('not-in-family', '2')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].str.replace('unmarried', '2')
InsClaims['insured_relationship'] = InsClaims['insured_relationship'].astype(int)

In [75]:
# Convert the 'umbrella_limit' variable into numeric

InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([-1000000], 1)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([2000000], 2)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([3000000], 3)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([4000000], 4)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([5000000], 5)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([6000000], 6)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([7000000], 7)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([8000000], 8)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([9000000], 9)
InsClaims['umbrella_limit'] = InsClaims['umbrella_limit'].replace([10000000], 10)

In [76]:
# Create capital gains ranges

InsClaims['CG_Range'] = pd.cut(x=InsClaims['capital-gains'], bins=[-1, 1, 10000, 20000, 30000, 40000, 50000,
75000, 105000],
labels=['0', '< 10K', '10K TO 20K', '20K TO 30K', '30K TO 40K', '40K TO 50K',
'50K TO 75K', '> 75K' ])

In [77]:
# Create capital gains ranges

InsClaims['CL_Range'] = pd.cut(x=InsClaims['capital-loss'], bins=[-115000, -75000, -50000, -40000,
-30000, -20000, -10000, -1, 1],
labels=['> -75K', '-50K TO -75K', '-40K TO -50K', '-30K TO -40K',
'-20K TO -30K', '-10K TO -20K', '< -10K', '0'])



In [78]:
# Convert the 'incident_type' to intergers

InsClaims['incident_type'] = InsClaims['incident_type'].str.replace('Parked Car', '1')
InsClaims['incident_type'] = InsClaims['incident_type'].str.replace('Single Vehicle Collision', '2')
InsClaims['incident_type'] = InsClaims['incident_type'].str.replace('Multi-vehicle Collision', '3')
InsClaims['incident_type'] = InsClaims['incident_type'].str.replace('Vehicle Theft', '4')
InsClaims['incident_type'] = InsClaims['incident_type'].astype(int)

# Convert the 'collision_type' to intergers

InsClaims['collision_type'] = InsClaims['collision_type'].str.replace('Rear Collision', '1')
InsClaims['collision_type'] = InsClaims['collision_type'].str.replace('?', '1')
InsClaims['collision_type'] = InsClaims['collision_type'].str.replace('Side Collision', '2')
InsClaims['collision_type'] = InsClaims['collision_type'].str.replace('Front Collision', '3')
InsClaims['collision_type'] = InsClaims['collision_type'].astype(int)

In [79]:
# Convert the 'incident_severity' to intergers

InsClaims['incident_severity'] = InsClaims['incident_severity'].str.replace('Minor Damage', '1')
InsClaims['incident_severity'] = InsClaims['incident_severity'].str.replace('Trivial Damage', '2')
InsClaims['incident_severity'] = InsClaims['incident_severity'].str.replace('Major Damage', '3')
InsClaims['incident_severity'] = InsClaims['incident_severity'].str.replace('Total Loss', '4')
InsClaims['incident_severity'] = InsClaims['incident_severity'].astype(int)

In [80]:
# Convert the 'authorities_contacted' to intergers

InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].str.replace('Police', '1')
InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].str.replace('Fire', '2')
InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].str.replace('Ambulance', '3')
InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].str.replace('Other', '4')
InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].str.replace('None', '4')
InsClaims['authorities_contacted'] = InsClaims['authorities_contacted'].astype(int)

In [81]:
# convert 'incident_hour_of_the_day' into ranges

InsClaims['Incident_Hour_Range'] = pd.cut(x=InsClaims['incident_hour_of_the_day'], bins=[-1, 4, 8, 12, 16, 20, 24],
labels=['12:00 AM to 04:00 AM', '04:00 AM to 08:00 AM', '08:00 AM to 12:00 PM',
'12:00 PM to 04:00 PM', '04:00 PM to 08:00 PM', '08:00 PM to 12:00 AM'])

In [82]:
# Convert 'property_damage' into integers

InsClaims['property_damage'] = InsClaims['property_damage'].str.replace('NO', '0')
InsClaims['property_damage'] = InsClaims['property_damage'].str.replace('YES', '1')
InsClaims['property_damage'] = InsClaims['property_damage'].str.replace('?', '1')
InsClaims['property_damage'] = InsClaims['property_damage'].astype(int)

In [83]:
# Convert 'police_report_available' into integers

InsClaims['police_report_available'] = InsClaims['police_report_available'].str.replace('NO', '2')
InsClaims['police_report_available'] = InsClaims['police_report_available'].str.replace('YES', '1')
InsClaims['police_report_available'] = InsClaims['police_report_available'].str.replace('?', '2')
InsClaims['police_report_available'] = InsClaims['police_report_available'].astype(int)

In [84]:
# Copy to new file which will used for classification analysis

InsClaimsF1 = InsClaims.copy()

In [85]:
# Dropping the variables which are impacting the target variable

InsClaimsF1 = InsClaimsF1.drop(['policy_number', 'months_as_customer', 'policy_bind_date', 'insured_zip',
'insured_occupation', 'insured_hobbies', 'capital-gains', 'capital-loss',
'incident_date', 'incident_state', 'incident_city', 'incident_location',
'incident_hour_of_the_day', 'auto_make', 'auto_model', 'auto_year'], axis=1)

In [86]:
# Create dummy variable for all range values

InsClaimsF1 = pd.get_dummies(InsClaimsF1, columns=['Range-mac', 'CG_Range', 'CL_Range',
'Incident_Hour_Range', 'insured_sex'])
InsClaimsF1.head().T

0        1         2  \
age                                          48.00    42.00     29.00   
policy_state                                  1.00     2.00      1.00   
policy_csl                                    2.00     2.00      1.00   
policy_deductable                          1000.00  2000.00   2000.00   
policy_annual_premium                      1406.91  1197.22   1413.14   
umbrella_limit                                0.00     5.00      5.00   
insured_education_level                       4.00     4.00      5.00   
insured_relationship                          1.00     1.00      1.00   
incident_type                                 2.00     4.00      3.00   
collision_type                                2.00     1.00      1.00   
incident_severity                             3.00     1.00      1.00   
authorities_contacted                         1.00     1.00      1.00   
number_of_vehicles_involved                   1.00     1.00      3.00   
property_damage                               1.00     1.00      0.00   
bodily_injuries                               1.00     0.00      2.00   
witnesses                                     2.00     0.00      3.00   
police_report_available                       1.00     2.00      2.00   
total_claim_amount                        71610.00  5070.00  34650.00   
injury_claim                               6510.00   780.00   7700.00   
property_claim                            13020.00   780.00   3850.00   
vehicle_claim                             52080.00  3510.00  23100.00   
fraud_reported                                1.00     1.00      0.00   
Range-mac_0 to 20                             0.00     0.00      0.00   
Range-mac_21 to 40                            0.00     0.00      0.00   
Range-mac_41 to 60                            0.00     0.00      0.00   
Range-mac_61 to 80                            0.00     0.00      0.00   
Range-mac_81 to 100                           0.00     0.00      0.00   
Range-mac_101 to 500                          1.00     1.00      1.00   
CG_Range_0                                    0.00     1.00      0.00   
CG_Range_< 10K                                0.00     0.00      0.00   
CG_Range_10K TO 20K                           0.00     0.00      0.00   
CG_Range_20K TO 30K                           0.00     0.00      0.00   
CG_Range_30K TO 40K                           0.00     0.00      1.00   
CG_Range_40K TO 50K                           0.00     0.00      0.00   
CG_Range_50K TO 75K                           1.00     0.00      0.00   
CG_Range_> 75K                                0.00     0.00      0.00   
CL_Range_> -75K                               0.00     0.00      0.00   
CL_Range_-50K TO -75K                         0.00     0.00      0.00   
CL_Range_-40K TO -50K                         0.00     0.00      0.00   
CL_Range_-30K TO -40K                         0.00     0.00      0.00   
CL_Range_-20K TO -30K                         0.00     0.00      0.00   
CL_Range_-10K TO -20K                         0.00     0.00      0.00   
CL_Range_< -10K                               0.00     0.00      0.00   
CL_Range_0                                    1.00     1.00      1.00   
Incident_Hour_Range_12:00 AM to 04:00 AM      0.00     0.00      0.00   
Incident_Hour_Range_04:00 AM to 08:00 AM      1.00     1.00      1.00   
Incident_Hour_Range_08:00 AM to 12:00 PM      0.00     0.00      0.00   
Incident_Hour_Range_12:00 PM to 04:00 PM      0.00     0.00      0.00   
Incident_Hour_Range_04:00 PM to 08:00 PM      0.00     0.00      0.00   
Incident_Hour_Range_08:00 PM to 12:00 AM      0.00     0.00      0.00   
insured_sex_FEMALE                            0.00     0.00      1.00   
insured_sex_MALE                              1.00     1.00      0.00   

                                                 3        4  
age                                          41.00    44.00  
policy_state                                  3.00     

In [87]:
# Identify the dependent and Target variables

IndepVar = []
for col in InsClaimsF1.columns:
    if col != 'fraud_reported':
        IndepVar.append(col)

TargetVar = 'fraud_reported'

x = InsClaimsF1[IndepVar]
y = InsClaimsF1[TargetVar]



In [88]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 6)
x_test_F1 = x_test.copy()

In [89]:
# Feature Scaling - Each independent variable is in different range. The process of transforming all the
# features in the given data set to a fixed range is known as ‘Scaling’

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# Conver x_train values

x_train['age'] = sc.fit_transform(x_train['age'].values.reshape(-1, 1))
x_train['policy_annual_premium'] = sc.fit_transform(x_train['policy_annual_premium'].values.reshape(-1, 1))
x_train['total_claim_amount'] = sc.fit_transform(x_train['total_claim_amount'].values.reshape(-1, 1))
x_train['injury_claim'] = sc.fit_transform(x_train['injury_claim'].values.reshape(-1, 1))
x_train['property_claim'] = sc.fit_transform(x_train['property_claim'].values.reshape(-1, 1))
x_train['vehicle_claim'] = sc.fit_transform(x_train['vehicle_claim'].values.reshape(-1, 1))

# Conver x_test values

x_test['age'] = sc.fit_transform(x_test['age'].values.reshape(-1, 1))
x_test['policy_annual_premium'] = sc.fit_transform(x_test['policy_annual_premium'].values.reshape(-1, 1))
x_test['total_claim_amount'] = sc.fit_transform(x_test['total_claim_amount'].values.reshape(-1, 1))
x_test['injury_claim'] = sc.fit_transform(x_test['injury_claim'].values.reshape(-1, 1))
x_test['property_claim'] = sc.fit_transform(x_test['property_claim'].values.reshape(-1, 1))
x_test['vehicle_claim'] = sc.fit_transform(x_test['vehicle_claim'].values.reshape(-1, 1))

# Convert to dataframes

x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)

# Random Forest without LDA/PCA

In [28]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                                criterion='entropy', max_depth=2, max_features='auto',
                                max_leaf_nodes=None, max_samples=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,
                                min_weight_fraction_leaf=0.0, n_estimators=500,
                                n_jobs=None, oob_score=False, random_state=0, verbose=0,
                                warm_start=False)

modelRF = modelRF.fit(x_train, y_train)

# Predict the model with test data set

y1_pred = modelRF.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y1_pred))
print(classification_report(y_test, y1_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y1_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y1_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y1_pred), 3))

[[228   0]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.66       300

Accuracy: 76.0 %
Precision: 76.0 %
Recall: 76.0 %
f1-score: 76.0 %
roc_auc_score: 0.5


# Decision Tree without LDA/PCA

In [29]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
max_depth=None, max_features=None, max_leaf_nodes=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
random_state=None, splitter='best')

modelDT = modelDT.fit(x_train,y_train)

# Predict with test data

y2_pred = modelDT.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y2_pred))
print(classification_report(y_test, y2_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y2_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y2_pred) * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y2_pred) * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y2_pred) * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y2_pred), 3))

[[186  42]
 [ 41  31]]
              precision    recall  f1-score   support

           0       0.82      0.82      0.82       228
           1       0.42      0.43      0.43        72

    accuracy                           0.72       300
   macro avg       0.62      0.62      0.62       300
weighted avg       0.72      0.72      0.72       300

Accuracy: 72.33 %
Precision: 42.47 %
Recall: 43.06 %
f1-score: 42.76 %
roc_auc_score: 0.623


# Logistic Regression without LDA/PCA

In [30]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x_train,y_train)

# Predict the model with test data set

y3_pred = modelLR.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y3_pred))
print(classification_report(y_test, y3_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y3_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y3_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y3_pred), 3))

[[217  11]
 [ 70   2]]
              precision    recall  f1-score   support

           0       0.76      0.95      0.84       228
           1       0.15      0.03      0.05        72

    accuracy                           0.73       300
   macro avg       0.45      0.49      0.44       300
weighted avg       0.61      0.73      0.65       300

Accuracy: 73.0 %
Precision: 73.0 %
Recall: 73.0 %
f1-score: 73.0 %
roc_auc_score: 0.49


# SVM - Gaussian without LDA/PCA

In [31]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, 
                          tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=- 1, 
                          decision_function_shape='ovr', break_ties=False, random_state=None)
modelSVMGaussian.fit(x_train, y_train)

# Predicting the values

y4_pred = modelSVMGaussian.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y4_pred))
print(classification_report(y_test,y4_pred))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y4_pred) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y4_pred, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y4_pred), 3))

[[228   0]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.66       300

Accuracy: 76.0 %
Precision: 76.0 %
Recall: 76.0 %
f1-score: 76.0 %
roc_auc_score: 0.5


# Appling PCA to all 5 Algorithm

In [59]:
from sklearn.decomposition import PCA

applyPCA = PCA()

x_train = applyPCA.fit_transform(x_train)
x_test = applyPCA.transform(x_test)
explained_variance = applyPCA.explained_variance_ratio_
print(explained_variance)

[9.99933893e-01 1.42918479e-05 9.66717712e-06 4.20294432e-06
 3.91395381e-06 3.69419067e-06 3.23001691e-06 3.12195255e-06
 2.76507673e-06 2.57753268e-06 1.90156998e-06 1.77888007e-06
 1.64639768e-06 1.47946731e-06 1.28697259e-06 1.17180331e-06
 8.70611864e-07 8.46752708e-07 8.07834582e-07 6.49108087e-07
 5.97970144e-07 5.51424916e-07 5.39476523e-07 5.16052045e-07
 4.51725292e-07 4.21046423e-07 4.12879521e-07 3.84596179e-07
 3.63822635e-07 3.39180272e-07 3.01374769e-07 2.61512274e-07
 2.11885891e-07 1.32663943e-07 1.26286156e-07 1.04269069e-07
 9.95637795e-08 9.32069326e-08 8.27998760e-08 7.29010915e-08
 6.44487095e-08 2.85685545e-08 2.50238000e-08 1.21647472e-08
 7.93970109e-09 9.96407041e-33 9.96407041e-33 9.96407041e-33
 9.96407041e-33 9.96407041e-33 9.96407041e-33]


# Random Forest with PCA

In [60]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                                criterion='entropy', max_depth=2, max_features='auto',
                                max_leaf_nodes=None, max_samples=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,
                                min_weight_fraction_leaf=0.0, n_estimators=500,
                                n_jobs=None, oob_score=False, random_state=0, verbose=0,
                                warm_start=False)

modelRF = modelRF.fit(x_train, y_train)

# Predict the model with test data set

y1_pred = modelRF.predict(x_test)
-
# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y1_pred))
print(classification_report(y_test, y1_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y1_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y1_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y1_pred), 3))

[[228   0]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.66       300

Accuracy: 76.0 %
Precision: 76.0 %
Recall: 76.0 %
f1-score: 76.0 %
roc_auc_score: 0.5


# Decision Tree with PCA

In [61]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
max_depth=None, max_features=None, max_leaf_nodes=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
random_state=None, splitter='best')

modelDT = modelDT.fit(x_train,y_train)

# Predict with test data

y2_pred = modelDT.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y2_pred))
print(classification_report(y_test, y2_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y2_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y2_pred) * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y2_pred) * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y2_pred) * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y2_pred), 3))

[[171  57]
 [ 40  32]]
              precision    recall  f1-score   support

           0       0.81      0.75      0.78       228
           1       0.36      0.44      0.40        72

    accuracy                           0.68       300
   macro avg       0.58      0.60      0.59       300
weighted avg       0.70      0.68      0.69       300

Accuracy: 67.67 %
Precision: 35.96 %
Recall: 44.44 %
f1-score: 39.75 %
roc_auc_score: 0.597


# Logistic Regression with PCA

In [62]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x_train,y_train)

# Predict the model with test data set

y3_pred = modelLR.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y3_pred))
print(classification_report(y_test, y3_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y3_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y3_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y3_pred), 3))

[[219   9]
 [ 69   3]]
              precision    recall  f1-score   support

           0       0.76      0.96      0.85       228
           1       0.25      0.04      0.07        72

    accuracy                           0.74       300
   macro avg       0.51      0.50      0.46       300
weighted avg       0.64      0.74      0.66       300

Accuracy: 74.0 %
Precision: 74.0 %
Recall: 74.0 %
f1-score: 74.0 %
roc_auc_score: 0.501


# SVM Gaussian with PCA

In [63]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, 
                          tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=- 1, 
                          decision_function_shape='ovr', break_ties=False, random_state=None)
modelSVMGaussian.fit(x_train, y_train)

# Predicting the values

y4_pred = modelSVMGaussian.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y4_pred))
print(classification_report(y_test,y4_pred))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y4_pred) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y4_pred, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y4_pred), 3))

[[228   0]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.66       300

Accuracy: 76.0 %
Precision: 76.0 %
Recall: 76.0 %
f1-score: 76.0 %
roc_auc_score: 0.5


# Appling all LCA algorithm with all 5

In [90]:
# Random forest with 'Linear Discriminant Analysis' technique to reduce the dimentionality

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

applyLDA = LinearDiscriminantAnalysis()

x_train = applyLDA.fit_transform(x_train, y_train)
x_test = applyLDA.transform(x_test)

explained_variance = applyLDA.explained_variance_ratio_
print(explained_variance)

[1.]


# Random Forest with LCA

In [92]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                                criterion='entropy', max_depth=2, max_features='auto',
                                max_leaf_nodes=None, max_samples=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,
                                min_weight_fraction_leaf=0.0, n_estimators=500,
                                n_jobs=None, oob_score=False, random_state=0, verbose=0,
                                warm_start=False)

modelRF = modelRF.fit(x_train, y_train)

# Predict the model with test data set

y1_pred = modelRF.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y1_pred))
print(classification_report(y_test, y1_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y1_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y1_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y1_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y1_pred), 3))

[[227   1]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.65       300

Accuracy: 75.67 %
Precision: 75.67 %
Recall: 75.67 %
f1-score: 75.67 %
roc_auc_score: 0.498


# Decision Tree with LCA

In [93]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
max_depth=None, max_features=None, max_leaf_nodes=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
random_state=None, splitter='best')

modelDT = modelDT.fit(x_train,y_train)

# Predict with test data

y2_pred = modelDT.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y2_pred))
print(classification_report(y_test, y2_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y2_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y2_pred) * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y2_pred) * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y2_pred) * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y2_pred), 3))

[[180  48]
 [ 54  18]]
              precision    recall  f1-score   support

           0       0.77      0.79      0.78       228
           1       0.27      0.25      0.26        72

    accuracy                           0.66       300
   macro avg       0.52      0.52      0.52       300
weighted avg       0.65      0.66      0.65       300

Accuracy: 66.0 %
Precision: 27.27 %
Recall: 25.0 %
f1-score: 26.09 %
roc_auc_score: 0.52


# Logistic Regression with LCA

In [94]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x_train,y_train)

# Predict the model with test data set

y3_pred = modelLR.predict(x_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y3_pred))
print(classification_report(y_test, y3_pred))

# Evaluate the model performance by metrics

from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", (round(metrics.accuracy_score(y_test, y3_pred) * 100, 2)), "%")

# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:", (round(metrics.precision_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:", (round(metrics.recall_score(y_test, y3_pred, average='micro') * 100, 2)), "%")

# Model f1-score: weighted average of Precision & Recall
print("f1-score:", (round(metrics.f1_score(y_test, y3_pred, average='micro') * 100, 2)), '%')

# Area under ROC curve
print('roc_auc_score:', round(roc_auc_score(y_test, y3_pred), 3))

[[216  12]
 [ 69   3]]
              precision    recall  f1-score   support

           0       0.76      0.95      0.84       228
           1       0.20      0.04      0.07        72

    accuracy                           0.73       300
   macro avg       0.48      0.49      0.46       300
weighted avg       0.62      0.73      0.66       300

Accuracy: 73.0 %
Precision: 73.0 %
Recall: 73.0 %
f1-score: 73.0 %
roc_auc_score: 0.495


# SVM Gaussian with LCA

In [95]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, 
                          tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=- 1, 
                          decision_function_shape='ovr', break_ties=False, random_state=None)
modelSVMGaussian.fit(x_train, y_train)

# Predicting the values

y4_pred = modelSVMGaussian.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y4_pred))
print(classification_report(y_test,y4_pred))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y4_pred) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y4_pred, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y4_pred, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y4_pred), 3))

[[227   1]
 [ 72   0]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       228
           1       0.00      0.00      0.00        72

    accuracy                           0.76       300
   macro avg       0.38      0.50      0.43       300
weighted avg       0.58      0.76      0.65       300

Accuracy: 75.67 %
Precision: 75.67 %
Recall: 75.67 %
f1-score: 75.67 %
roc_auc_score: 0.498
