# Credit_Card

In [1]:
# Importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ignore harmful warnings
import warnings
warnings.filterwarnings('ignore')

import pandasql as psql

In [2]:
# Load the Defult Credit Card cilents data

dccdata = pd.read_csv(r"D:\iiit notes\Programming\AI\Internship practice\44 season 19-jul-2021\Default_Credit_Card_Clients_SVM.csv",header = 0)
dccdata.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

In [3]:
dccdata.rename({'default payment next month' : 'CC_Default'}, axis =1, inplace=True)
dccdata.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  CC_Default  
0         0         0         0           1  
1      1000         0      2000           1  
2      1000      1000      5000           0  
3      1100      1069      1000           0  
4      9000       689       679           0  

[5 rows x 25 columns]

In [4]:
# Count the target or dependent variable by '0' or '1' and
# their proportion (> 10: 1, then the dataset is imbalance dataset

dccdata_count = dccdata.CC_Default.value_counts()
print('Class 0: ', dccdata_count[0])
print('Class 1: ', dccdata_count[1])
print('Proportion: ', round(dccdata_count[0]/dccdata_count[1], 2), ': 1')
print('Total CC Trans: ', len(dccdata)) 

Class 0:  23364
Class 1:  6636
Proportion:  3.52 : 1
Total CC Trans:  30000


In [5]:
# count of eduction variable

dccdata['EDUCATION'].value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: EDUCATION, dtype: int64

In [6]:
dccdata['MARRIAGE'].value_counts()

2    15964
1    13659
3      323
0       54
Name: MARRIAGE, dtype: int64

In [7]:
# Missing value data size

dccdata_missing = (dccdata[(dccdata.EDUCATION == 0) | (dccdata.MARRIAGE == 0)])
dccdata_missing.shape

(68, 25)

In [8]:
dccdata_no_missing = dccdata[(dccdata.EDUCATION != 0) | (dccdata.MARRIAGE != 0)]
dccdata_no_missing.shape

(30000, 25)

In [9]:
dccdata1 = dccdata_no_missing.copy()
dccdata1.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  CC_Default  
0         0         0         0           1  
1      1000         0      2000           1  
2      1000      1000      5000           0  
3      1100      1069      1000           0  
4      9000       689       679           0  

[5 rows x 25 columns]

In [10]:
# Convert into dummies

dccdata1 = pd.get_dummies(dccdata1, columns=['SEX','EDUCATION','MARRIAGE','PAY_1','PAY_2',
                                            'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6'])
dccdata1.head()

ID  LIMIT_BAL  AGE  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0   1      20000   24       3913       3102        689          0          0   
1   2     120000   26       2682       1725       2682       3272       3455   
2   3      90000   34      29239      14027      13559      14331      14948   
3   4      50000   37      46990      48233      49291      28314      28959   
4   5      50000   57       8617       5670      35835      20940      19146   

   BILL_AMT6  PAY_AMT1  ...  PAY_6_-2  PAY_6_-1  PAY_6_0  PAY_6_2  PAY_6_3  \
0          0         0  ...         1         0        0        0        0   
1       3261         0  ...         0         0        0        1        0   
2      15549      1518  ...         0         0        1        0        0   
3      29547      2000  ...         0         0        1        0        0   
4      19131      2000  ...         0         0        1        0        0   

   PAY_6_4  PAY_6_5  PAY_6_6  PAY_6_7  PAY_6_8  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0  

[5 rows x 93 columns]

In [11]:
cols = ['LIMIT_BAL','AGE','BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

In [12]:
# Identify independent and target variable

x = dccdata1.drop(['CC_Default', 'ID'], axis=1)
y = dccdata1['CC_Default']

In [13]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state = 4)
x_test_f1 = x_test.copy()

In [14]:
# Scaling the features by using MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

mmscaler = MinMaxScaler(feature_range=(0, 1))

x_train[cols] = mmscaler.fit_transform(x_train[cols])
x_train = pd.DataFrame(x_train)

x_test[cols] = mmscaler.fit_transform(x_test[cols])
x_test = pd.DataFrame(x_test)

# Random Forest without LDA & PCA

In [15]:
# Build Random Forest Classification model and train model using the training dataset

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(n_estimators=500, criterion='entropy', max_depth=2, min_samples_split=2, min_samples_leaf=1, 
                                 min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, 
                                 min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, 
                                 n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, 
                                 ccp_alpha=0.0, max_samples=None)

modelRF = modelRF.fit(x_train, y_train)

# Predict the model with the test data set

y_pred = modelRF.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred), 3))

Confusion matrix : 
 [[  38 1993]
 [   9 6960]]
Outcome Values : 
 38 1993 9 6960
Classification report : 
               precision    recall  f1-score   support

           1       0.81      0.02      0.04      2031
           0       0.78      1.00      0.87      6969

    accuracy                           0.78      9000
   macro avg       0.79      0.51      0.46      9000
weighted avg       0.78      0.78      0.69      9000

Accuracy : 77.8 %
Precision : 80.9 %
Recall : 1.9 %
F1 Score : 0.037
Balanced Accuracy : 50.9 %
MCC 0.101
roc_auc_score: 0.509


# Logistic Regression without LDA & PCA

In [16]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                            intercept_scaling=1, max_iter=100, multi_class='auto',
                            n_jobs=None, penalty='l2', random_state=None,
                            solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x_train,y_train)

# Predict the model with test data set

y1_pred = modelLR.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y1_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y1_pred), 3))

Confusion matrix : 
 [[ 683 1348]
 [ 311 6658]]
Outcome Values : 
 683 1348 311 6658
Classification report : 
               precision    recall  f1-score   support

           1       0.69      0.34      0.45      2031
           0       0.83      0.96      0.89      6969

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.67      9000
weighted avg       0.80      0.82      0.79      9000

Accuracy : 81.6 %
Precision : 68.7 %
Recall : 33.6 %
F1 Score : 0.452
Balanced Accuracy : 64.6 %
MCC 0.389
roc_auc_score: 0.646


# Decision Tree without PCA & LCA

In [17]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                                max_depth=None, max_features=None, max_leaf_nodes=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
                                random_state=None, splitter='best')

modelDT = modelDT.fit(x_train,y_train)

# Predict with test data

y2_pred = modelDT.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y2_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y2_pred), 3))

Confusion matrix : 
 [[ 901 1130]
 [3592 3377]]
Outcome Values : 
 901 1130 3592 3377
Classification report : 
               precision    recall  f1-score   support

           1       0.20      0.44      0.28      2031
           0       0.75      0.48      0.59      6969

    accuracy                           0.48      9000
   macro avg       0.47      0.46      0.43      9000
weighted avg       0.63      0.48      0.52      9000

Accuracy : 47.5 %
Precision : 20.1 %
Recall : 44.4 %
F1 Score : 0.276
Balanced Accuracy : 46.4 %
MCC -0.06
roc_auc_score: 0.464


# SVM without PCA & LCA

In [18]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(kernel='rbf', random_state = 42, class_weight='balanced')
modelSVMGaussian.fit(x_train, y_train)

# Predicting the values

y3_pred = modelSVMGaussian.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y3_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y3_pred), 3))

Confusion matrix : 
 [[1187  844]
 [1226 5743]]
Outcome Values : 
 1187 844 1226 5743
Classification report : 
               precision    recall  f1-score   support

           1       0.49      0.58      0.53      2031
           0       0.87      0.82      0.85      6969

    accuracy                           0.77      9000
   macro avg       0.68      0.70      0.69      9000
weighted avg       0.79      0.77      0.78      9000

Accuracy : 77.0 %
Precision : 49.2 %
Recall : 58.4 %
F1 Score : 0.534
Balanced Accuracy : 70.4 %
MCC 0.386
roc_auc_score: 0.704


# KNN Without PCA & LCA

In [19]:
# Build the algorithm with KNN

from sklearn import neighbors

modelKNN = neighbors.KNeighborsClassifier(n_neighbors=5,weights='uniform', algorithm='auto', leaf_size=30, p=2, 
                                          metric='minkowski', metric_params=None, n_jobs=None)
modelKNN.fit(x_train, y_train)

# Predict the model with test dataset

y4_pred = modelKNN.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y4_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y4_pred), 3))

Confusion matrix : 
 [[ 719 1312]
 [ 601 6368]]
Outcome Values : 
 719 1312 601 6368
Classification report : 
               precision    recall  f1-score   support

           1       0.54      0.35      0.43      2031
           0       0.83      0.91      0.87      6969

    accuracy                           0.79      9000
   macro avg       0.69      0.63      0.65      9000
weighted avg       0.76      0.79      0.77      9000

Accuracy : 78.7 %
Precision : 54.5 %
Recall : 35.4 %
F1 Score : 0.429
Balanced Accuracy : 63.4 %
MCC 0.316
roc_auc_score: 0.634


# Train the Principal Component Analysis (PCA) with train data and test data

In [20]:
# Principal component analysis (PCA) is a statistical technique to convert high dimensional data to low dimensional data
# by selecting the most important features that capture maximum information about the dataset. The features are selected
# on the basis of variance that they cause in the output. The feature that causes highest variance is the first principal
# component. The feature that is responsible for second highest variance is considered the second principal component,
# and so on. It is important to mention that principal components do not have any correlation with each other.

from sklearn.decomposition import PCA

applyPCA = PCA()

x1_train = applyPCA.fit_transform(x_train)
x1_test = applyPCA.transform(x_test)
explained_variance = applyPCA.explained_variance_ratio_
print(explained_variance)

[2.63074743e-01 1.19175438e-01 9.49995740e-02 8.62684840e-02
 7.79871033e-02 6.26361788e-02 4.47164916e-02 3.50003171e-02
 2.66290656e-02 2.43307918e-02 1.88796575e-02 1.80620225e-02
 1.42211825e-02 1.37858060e-02 1.27145548e-02 1.09042849e-02
 8.76980766e-03 8.23317404e-03 7.13601544e-03 6.94376454e-03
 6.12163231e-03 4.35849301e-03 3.54754844e-03 3.28083811e-03
 2.81058076e-03 2.52939691e-03 2.41646883e-03 2.36586330e-03
 2.12120668e-03 1.97047226e-03 1.91574688e-03 1.56381366e-03
 1.23975531e-03 1.07095230e-03 9.83863328e-04 9.34224028e-04
 7.62139588e-04 5.62550705e-04 4.96694519e-04 4.04452722e-04
 3.95172688e-04 3.48325734e-04 3.20718479e-04 2.95185665e-04
 2.86223358e-04 2.24530677e-04 2.12042977e-04 1.90053909e-04
 1.80771219e-04 1.48981420e-04 1.38899162e-04 1.32499430e-04
 1.20262687e-04 1.07201504e-04 1.06431318e-04 1.04477634e-04
 9.35733486e-05 8.16416203e-05 7.46262915e-05 7.13956208e-05
 6.96779771e-05 5.10489273e-05 4.19469611e-05 3.61923219e-05
 3.21367166e-05 2.870610

# Random Forest with PCA

In [21]:
# Build Random Forest Classification model and train model using the training dataset

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(n_estimators=500, criterion='entropy', max_depth=2, min_samples_split=2, min_samples_leaf=1, 
                                 min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, 
                                 min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, 
                                 n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, 
                                 ccp_alpha=0.0, max_samples=None)

modelRF = modelRF.fit(x1_train, y_train)

# Predict the model with the test data set

y5_pred = modelRF.predict(x1_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y5_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y5_pred), 3))

Confusion matrix : 
 [[ 180 1851]
 [  64 6905]]
Outcome Values : 
 180 1851 64 6905
Classification report : 
               precision    recall  f1-score   support

           1       0.74      0.09      0.16      2031
           0       0.79      0.99      0.88      6969

    accuracy                           0.79      9000
   macro avg       0.76      0.54      0.52      9000
weighted avg       0.78      0.79      0.72      9000

Accuracy : 78.7 %
Precision : 73.8 %
Recall : 8.9 %
F1 Score : 0.158
Balanced Accuracy : 54.0 %
MCC 0.204
roc_auc_score: 0.54


# Logistic Regression with PCA

In [22]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                            intercept_scaling=1, max_iter=100, multi_class='auto',
                            n_jobs=None, penalty='l2', random_state=None,
                            solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x1_train,y_train)

# Predict the model with test data set

y6_pred = modelLR.predict(x1_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y6_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y6_pred), 3))

Confusion matrix : 
 [[ 680 1351]
 [ 307 6662]]
Outcome Values : 
 680 1351 307 6662
Classification report : 
               precision    recall  f1-score   support

           1       0.69      0.33      0.45      2031
           0       0.83      0.96      0.89      6969

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.67      9000
weighted avg       0.80      0.82      0.79      9000

Accuracy : 81.6 %
Precision : 68.9 %
Recall : 33.5 %
F1 Score : 0.451
Balanced Accuracy : 64.6 %
MCC 0.389
roc_auc_score: 0.645


# Decision Tree with PCA

In [23]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                                max_depth=None, max_features=None, max_leaf_nodes=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
                                random_state=None, splitter='best')

modelDT = modelDT.fit(x1_train,y_train)

# Predict with test data

y7_pred = modelDT.predict(x1_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y7_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y7_pred), 3))

Confusion matrix : 
 [[ 820 1211]
 [1840 5129]]
Outcome Values : 
 820 1211 1840 5129
Classification report : 
               precision    recall  f1-score   support

           1       0.31      0.40      0.35      2031
           0       0.81      0.74      0.77      6969

    accuracy                           0.66      9000
   macro avg       0.56      0.57      0.56      9000
weighted avg       0.70      0.66      0.68      9000

Accuracy : 66.1 %
Precision : 30.8 %
Recall : 40.4 %
F1 Score : 0.35
Balanced Accuracy : 57.0 %
MCC 0.128
roc_auc_score: 0.57


# SVM with PCA

In [24]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(kernel='rbf', random_state = 42, class_weight='balanced')

modelSVMGaussian.fit(x1_train, y_train)

# Predicting the values

y8_pred = modelSVMGaussian.predict(x1_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y8_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y8_pred), 3))

Confusion matrix : 
 [[1201  830]
 [1285 5684]]
Outcome Values : 
 1201 830 1285 5684
Classification report : 
               precision    recall  f1-score   support

           1       0.48      0.59      0.53      2031
           0       0.87      0.82      0.84      6969

    accuracy                           0.77      9000
   macro avg       0.68      0.70      0.69      9000
weighted avg       0.78      0.77      0.77      9000

Accuracy : 76.5 %
Precision : 48.3 %
Recall : 59.1 %
F1 Score : 0.532
Balanced Accuracy : 70.4 %
MCC 0.38
roc_auc_score: 0.703


# KNN with PCA

In [25]:
# Build the algorithm with KNN

from sklearn import neighbors

modelKNN = neighbors.KNeighborsClassifier(n_neighbors=5,weights='uniform', algorithm='auto', leaf_size=30, p=2, 
                                          metric='minkowski', metric_params=None, n_jobs=None)
modelKNN.fit(x1_train, y_train)

# Predict the model with test dataset

y9_pred = modelKNN.predict(x1_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y9_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y9_pred), 3))

Confusion matrix : 
 [[ 719 1312]
 [ 601 6368]]
Outcome Values : 
 719 1312 601 6368
Classification report : 
               precision    recall  f1-score   support

           1       0.54      0.35      0.43      2031
           0       0.83      0.91      0.87      6969

    accuracy                           0.79      9000
   macro avg       0.69      0.63      0.65      9000
weighted avg       0.76      0.79      0.77      9000

Accuracy : 78.7 %
Precision : 54.5 %
Recall : 35.4 %
F1 Score : 0.429
Balanced Accuracy : 63.4 %
MCC 0.316
roc_auc_score: 0.634


# Train the Linear Discriminant Analysis (LDA) with train data and test data

In [26]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

applyLDA = LinearDiscriminantAnalysis()

x2_train = applyLDA.fit_transform(x_train, y_train)
x2_test = applyLDA.transform(x_test)

explained_variance = applyLDA.explained_variance_ratio_
print(explained_variance)

[1.]


# Random Forest with LDA

In [27]:
# Build Random Forest Classification model and train model using the training dataset

from sklearn.ensemble import RandomForestClassifier

modelRF = RandomForestClassifier(n_estimators=500, criterion='entropy', max_depth=2, min_samples_split=2, min_samples_leaf=1, 
                                 min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, 
                                 min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, 
                                 n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, 
                                 ccp_alpha=0.0, max_samples=None)

modelRF = modelRF.fit(x2_train, y_train)

# Predict the model with the test data set

y10_pred = modelRF.predict(x2_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y10_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y10_pred), 3))

Confusion matrix : 
 [[ 576 1455]
 [ 245 6724]]
Outcome Values : 
 576 1455 245 6724
Classification report : 
               precision    recall  f1-score   support

           1       0.70      0.28      0.40      2031
           0       0.82      0.96      0.89      6969

    accuracy                           0.81      9000
   macro avg       0.76      0.62      0.65      9000
weighted avg       0.79      0.81      0.78      9000

Accuracy : 81.1 %
Precision : 70.2 %
Recall : 28.4 %
F1 Score : 0.404
Balanced Accuracy : 62.4 %
MCC 0.361
roc_auc_score: 0.624


# Logistic Regression with LDA

In [28]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

modelLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                            intercept_scaling=1, max_iter=100, multi_class='auto',
                            n_jobs=None, penalty='l2', random_state=None,
                            solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

modelLR = modelLR.fit(x2_train,y_train)

# Predict the model with test data set

y11_pred = modelLR.predict(x2_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y11_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y11_pred), 3))

Confusion matrix : 
 [[ 680 1351]
 [ 311 6658]]
Outcome Values : 
 680 1351 311 6658
Classification report : 
               precision    recall  f1-score   support

           1       0.69      0.33      0.45      2031
           0       0.83      0.96      0.89      6969

    accuracy                           0.82      9000
   macro avg       0.76      0.65      0.67      9000
weighted avg       0.80      0.82      0.79      9000

Accuracy : 81.5 %
Precision : 68.6 %
Recall : 33.5 %
F1 Score : 0.45
Balanced Accuracy : 64.5 %
MCC 0.388
roc_auc_score: 0.645


# Decision Tree with LDA

In [29]:
# To build the decision tree model with Over sampling

from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                                max_depth=None, max_features=None, max_leaf_nodes=None,
                                min_impurity_decrease=0.0, min_impurity_split=None,
                                min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
                                random_state=None, splitter='best')

modelDT = modelDT.fit(x2_train,y_train)

# Predict with test data

y12_pred = modelDT.predict(x2_test)

# Display confusion matrix and classifiction report

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y12_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y12_pred), 3))

Confusion matrix : 
 [[ 669 1362]
 [1038 5931]]
Outcome Values : 
 669 1362 1038 5931
Classification report : 
               precision    recall  f1-score   support

           1       0.39      0.33      0.36      2031
           0       0.81      0.85      0.83      6969

    accuracy                           0.73      9000
   macro avg       0.60      0.59      0.59      9000
weighted avg       0.72      0.73      0.72      9000

Accuracy : 73.3 %
Precision : 39.2 %
Recall : 32.9 %
F1 Score : 0.358
Balanced Accuracy : 59.0 %
MCC 0.192
roc_auc_score: 0.59


# SVM with LDA

In [30]:
# Training the SVM algorithm

from sklearn.svm import SVC

modelSVMGaussian = SVC(kernel='rbf', random_state = 42, class_weight='balanced')

modelSVMGaussian.fit(x2_train, y_train)

# Predicting the values

y13_pred = modelSVMGaussian.predict(x2_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y13_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y13_pred), 3))

Confusion matrix : 
 [[1102  929]
 [ 932 6037]]
Outcome Values : 
 1102 929 932 6037
Classification report : 
               precision    recall  f1-score   support

           1       0.54      0.54      0.54      2031
           0       0.87      0.87      0.87      6969

    accuracy                           0.79      9000
   macro avg       0.70      0.70      0.70      9000
weighted avg       0.79      0.79      0.79      9000

Accuracy : 79.3 %
Precision : 54.2 %
Recall : 54.3 %
F1 Score : 0.542
Balanced Accuracy : 70.4 %
MCC 0.409
roc_auc_score: 0.704


# KNN with LDA

In [31]:
# Build the algorithm with KNN

from sklearn import neighbors

modelKNN = neighbors.KNeighborsClassifier(n_neighbors=5,weights='uniform', algorithm='auto', leaf_size=30, p=2, 
                                          metric='minkowski', metric_params=None, n_jobs=None)
modelKNN.fit(x2_train, y_train)

# Predict the model with test dataset

y14_pred = modelKNN.predict(x2_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y14_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y14_pred), 3))

Confusion matrix : 
 [[ 648 1383]
 [ 458 6511]]
Outcome Values : 
 648 1383 458 6511
Classification report : 
               precision    recall  f1-score   support

           1       0.59      0.32      0.41      2031
           0       0.82      0.93      0.88      6969

    accuracy                           0.80      9000
   macro avg       0.71      0.63      0.64      9000
weighted avg       0.77      0.80      0.77      9000

Accuracy : 79.5 %
Precision : 58.6 %
Recall : 31.9 %
F1 Score : 0.413
Balanced Accuracy : 62.6 %
MCC 0.323
roc_auc_score: 0.627
