In [23]:
# Importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Ignore warnings

import warnings
warnings.filterwarnings('ignore')

import pandasql as psql

In [24]:
# load the Auto Quote ins data

AutoIns = pd.read_csv(r"D:\iiit_notes\Programming\AI\Internship practice\Project-01\Auto_Quote_Data_V1.0.csv", header=0)
AutoIns.head()

Quote_Num Agent_Type Q_Creation_DT  Q_Valid_DT Policy_Bind_DT Region  \
0  AQ-C-139212         EA    2020/04/25  2020/06/23     2020/05/23      C   
1  AQ-F-136117         EA    2020/02/21  2020/04/20            NaN      F   
2  AQ-F-126801         EA    2020/06/19  2020/08/17     2020/07/12      F   
3  AQ-E-143467         EA    2020/05/02  2020/06/30     2020/05/24      E   
4  AQ-C-143827         EA    2020/02/12  2020/04/11     2020/02/25      C   

   Agent_Num Policy_Type  HH_Vehicles  HH_Drivers  ...  Marital_Status  \
0       2156         Car            3           3  ...           Widow   
1       2153         Van            2           2  ...       Dirvorced   
2       2056       Truck            2           1  ...       Dirvorced   
3       2138         Car            1           2  ...         Married   
4       2327       Truck            3           1  ...           Widow   

     Education           Sal_Range  Coverage Veh_Usage Annual_Miles_Range  \
0  High School  > $ 25 K <= $ 40 K  Balanced   Commute             > 55 K   
1         Ph.D  > $ 40 K <= $ 60 K  Balanced  Pleasure  > 7.5 K & <= 15 K   
2         Ph.D  > $ 40 K <= $ 60 K     Basic   Commute   > 35 K & <= 45 K   
3         Ph.D           > $ 90 K      Basic  Pleasure           <= 7.5 K   
4  High School           <= $ 25 K     Basic  Pleasure   > 35 K & <= 45 K   

    Vehicl_Cost_Range Re_Quote Quoted_Premium Policy_Bind  
0  > $ 10 K <= $ 20 K       No         693.86         Yes  
1           <= $ 10 K       No         635.96          No  
2  > $ 10 K <= $ 20 K       No         780.64         Yes  
3           <= $ 10 K       No         723.15         Yes  
4           <= $ 10 K       No         738.14         Yes  

[5 rows x 25 columns]

In [25]:
AutoIns.shape

(146259, 25)

In [26]:
# Convert the target varaible data type into integer
AutoIns['Policy_Bind'] = AutoIns['Policy_Bind'].str.replace('No', '0')
AutoIns['Policy_Bind'] = AutoIns['Policy_Bind'].str.replace('Yes', '1')
AutoIns['Policy_Bind'] = AutoIns['Policy_Bind'].astype(int)

In [27]:
# Count the target or dependent varaible by '0' or '1' and
# their proportion (> 10 : 1, then the dataset is imbalance dataset)

Policy_Bind_count = AutoIns.Policy_Bind.value_counts()
print('Class 0:', Policy_Bind_count[0])
print('Class 1:', Policy_Bind_count[1])
print('Proportion:', round(Policy_Bind_count[0]/ Policy_Bind_count[1], 2), ': 1')
print('Total Records:', len(AutoIns))

Class 0: 113757
Class 1: 32502
Proportion: 3.5 : 1
Total Records: 146259


In [28]:
# Display the Dataset information 

AutoIns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146259 entries, 0 to 146258
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Quote_Num           146259 non-null  object 
 1   Agent_Type          146259 non-null  object 
 2   Q_Creation_DT       146259 non-null  object 
 3   Q_Valid_DT          146259 non-null  object 
 4   Policy_Bind_DT      32502 non-null   object 
 5   Region              146259 non-null  object 
 6   Agent_Num           146259 non-null  int64  
 7   Policy_Type         146259 non-null  object 
 8   HH_Vehicles         146259 non-null  int64  
 9   HH_Drivers          146259 non-null  int64  
 10  Driver_Age          146259 non-null  int64  
 11  Driving_Exp         146259 non-null  int64  
 12  Prev_Accidents      146259 non-null  int64  
 13  Prev_Citations      146259 non-null  int64  
 14  Gender              146259 non-null  object 
 15  Marital_Status      146259 non-nul

In [16]:
# Ranges and new column as 'QP_Range' from 'Quoted_premium'

AutoIns['QP_Range'] = pd.cut(AutoIns['Quoted_Premium'], [0, 800, 1000, 1200, 9999],
                             labels = ['0-800', '801-1000', '1001-1200', '>1200'])

In [18]:
# Dropping the varaibles which are not impacting the target variable

AutoIns = AutoIns.drop(['Quote_Num', 'Agent_Num', 'Q_Creation_DT',
                        'Q_Valid_DT', 'Policy_Bind_DT', 'Sal_Range',
                        'Vehicl_Cost_Range', 'Quoted_Premium'], axis=1)

In [20]:
AutoIns = pd.get_dummies(AutoIns, columns=['Agent_Type','Region', 'Policy_Type', 'Gender', 'Marital_Status', 'Education',
                                           'Coverage', 'Veh_Usage', 'Annual_Miles_Range', 
                                          'Re_Quote', 'QP_Range'])

In [21]:
# Displaying the dataset after converting categorical to numeric data

AutoIns.head()

HH_Vehicles  HH_Drivers  Driver_Age  Driving_Exp  Prev_Accidents  \
0            3           3          43           26               0   
1            2           2          30           13               0   
2            2           1          25            8               0   
3            1           2          43           26               0   
4            3           1          40           23               0   

   Prev_Citations  Policy_Bind  Agent_Type_EA  Agent_Type_IA  Region_A  ...  \
0               0            1              1              0         0  ...   
1               0            0              1              0         0  ...   
2               0            1              1              0         0  ...   
3               0            1              1              0         0  ...   
4               0            1              1              0         0  ...   

   Annual_Miles_Range_> 35 K & <= 45 K  Annual_Miles_Range_> 45 K & <= 55 K  \
0                                    0                                    0   
1                                    0                                    0   
2                                    1                                    0   
3                                    0                                    0   
4                                    1                                    0   

   Annual_Miles_Range_> 55 K  Annual_Miles_Range_> 7.5 K & <= 15 K  \
0                          1                                     0   
1                          0                                     1   
2                          0                                     0   
3                          0                                     0   
4                          0                                     0   

   Re_Quote_No  Re_Quote_Yes  QP_Range_0-800  QP_Range_801-1000  \
0            1             0               1                  0   
1            1             0               1                  0   
2            1             0               1                  0   
3            1             0               1                  0   
4            1             0               1                  0   

   QP_Range_1001-1200  QP_Range_>1200  
0                   0               0  
1                   0               0  
2                   0               0  
3                   0               0  
4                   0               0  

[5 rows x 50 columns]

In [22]:
AutoIns.shape

(146259, 50)

In [ ]:
# Identify the dependent and Target variables

IndepVar =[]
for col in AutoIns.columns:
    if col != 'Policy_Bind':
        IndepVar.append(col)
        
TargetVar = 'Policy_Bind'
x = AutoIns[IndepVar]
y = AutoIns[TargetVar]

In [11]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

# DECISION TREE

# Decision Tree with random sampling

In [12]:
# Feature Scaling - Each independent variable is in different range. The process of transforming all the
# features in the given data set to a fixed range is known as 'Scaling'

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train['Driver_Age'] = sc.fit_transform(x_train['Driver_Age'].values.reshape(-1, 1))
x_train['Driving_Exp'] = sc.fit_transform(x_train['Driving_Exp'].values.reshape(-1, 1))
x_test['Driver_Age'] = sc.fit_transform(x_test['Driver_Age'].values.reshape(-1, 1)) 
x_test['Driving_Exp'] = sc.fit_transform(x_test['Driving_Exp'].values.reshape(-1, 1)) 
# Convert to dataframe x_train = pd.DataFrame(x_train) x_test = pd.DataFrame(x_test)

In [13]:
# Build the decision tree model with random sampling and Train the model

from sklearn.tree import DecisionTreeClassifier 
AutoInsDT = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini', max_depth=None, 
                                   max_features=None, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                                   min_impurity_split=None, min_samples_leaf=1, min_samples_split=2,
                                   min_weight_fraction_leaf=0.0, random_state=None, splitter='best') 
AutoInsDT = AutoInsDT.fit(x_train,y_train)

In [14]:
# Predict the model with test data 
    
y_pred = AutoInsDT.predict(x_test)
    
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = y_test

# predicted values 

predicted = y_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC) 

Confusion matrix : 
 [[ 2411  7405]
 [ 8686 25376]]
Outcome values : 
 2411 7405 8686 25376
Classification report : 
               precision    recall  f1-score   support

           1       0.22      0.25      0.23      9816
           0       0.77      0.74      0.76     34062

    accuracy                           0.63     43878
   macro avg       0.50      0.50      0.49     43878
weighted avg       0.65      0.63      0.64     43878

Accuracy : 63.3 %
Precision : 21.7 %
Recall : 24.6 %
F1 Score : 0.231
Balanced Accuracy : 49.6 %
MCC : -0.009


In [15]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score1 = AutoInsDT.predict_proba(x_test)[:,1] 
    
false_positive_rate1, true_positive_rate1, threshold1 = roc_curve(y_test, y_score1) 
    
print('roc_auc_score:', round(roc_auc_score(y_test, y_score1), 3))

roc_auc_score: 0.495


# Decision tree with Over sampling

In [16]:
# Random oversampling can be implemented using the RandomOverSampler class

from imblearn.over_sampling import RandomOverSampler

oversample = RandomOverSampler(sampling_strategy='minority')
x_over, y_over = oversample.fit_resample(x, y)
print(x_over.shape)
print(y_over.shape)

(227514, 59)
(227514,)


In [17]:
# To know the count of major and minor classes

y_over.value_counts()

0    113757
1    113757
Name: Policy_Bind, dtype: int64

In [18]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split

xo_train, xo_test, yo_train, yo_test = train_test_split(x_over, y_over, test_size = 0.3, random_state=42)

In [19]:
# Feature Scaling - Each independent variable is in different range. The process of transforming all the
# features in the given data set to a fixed range is known as ‘Scaling’

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

#x_train = sc.fit_transform(x_train)
#x_test = sc.fit_transform(x_test)

xo_train['Driver_Age'] = sc.fit_transform(xo_train['Driver_Age'].values.reshape(-1, 1))
xo_train['Driving_Exp'] = sc.fit_transform(xo_train['Driving_Exp'].values.reshape(-1, 1))
xo_test['Driver_Age'] = sc.fit_transform(xo_test['Driver_Age'].values.reshape(-1, 1))
xo_test['Driving_Exp'] = sc.fit_transform(xo_test['Driving_Exp'].values.reshape(-1, 1))

# convert to dataframe

xo_train = pd.DataFrame(xo_train)
xo_test = pd.DataFrame(xo_test)

In [20]:
# To build the decision tree model with Under Sampling

from sklearn.tree import DecisionTreeClassifier

AutoInsDT_O = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                                      max_depth=None, max_features=None, max_leaf_nodes=None,
                                      min_impurity_decrease=0.0, min_impurity_split=None,
                                      min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
                                      random_state=None, splitter='best')

AutoInsDT_O = AutoInsDT_O.fit(xo_train, yo_train)

In [21]:
# Predict with test data

yo_pred = AutoInsDT_O.predict(xo_test)

In [22]:
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yo_test

# predicted values 

predicted = yo_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC) 

Confusion matrix : 
 [[32119  2059]
 [ 9940 24137]]
Outcome values : 
 32119 2059 9940 24137
Classification report : 
               precision    recall  f1-score   support

           1       0.76      0.94      0.84     34178
           0       0.92      0.71      0.80     34077

    accuracy                           0.82     68255
   macro avg       0.84      0.82      0.82     68255
weighted avg       0.84      0.82      0.82     68255

Accuracy : 82.4 %
Precision : 76.4 %
Recall : 94.0 %
F1 Score : 0.843
Balanced Accuracy : 82.4 %
MCC : 0.666


In [23]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score2 = AutoInsDT_O.predict_proba(xo_test)[:,1] 
    
false_positive_rate2, true_positive_rate2, threshold2 = roc_curve(yo_test, y_score2) 
    
print('roc_auc_score:', round(roc_auc_score(yo_test, y_score2), 3))

roc_auc_score: 0.824


# Combining Under & Oversampling - Decision Tree

In [24]:
# Combining Random Oversampling and Undersampling 

from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

# define oversampling strategy

over = RandomOverSampler(sampling_strategy=0.70)

# fit and apply the transform

x2, y2 = over.fit_resample(x,y)
print(x2.shape)
print(y2.shape)

# define undersampling strategy

under = RandomUnderSampler(sampling_strategy=0.70)

# fit and apply the transform

x3, y3 = under.fit_resample(x2, y2)

print(x3.shape)
print(y3.shape)


(193386, 59)
(193386,)
(193384, 59)
(193384,)


In [25]:
# To know the count of major and minor classes

y3.value_counts()

0    113755
1     79629
Name: Policy_Bind, dtype: int64

In [26]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split

xc_train, xc_test, yc_train, yc_test = train_test_split(x3, y3, test_size = 0.30, random_state = 42)


In [27]:
# Feature Scaling - Each independent variable is in different range. The process of transforming all the
# features in the given data set to a fixed range is known as ‘Scaling’

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

xc_train['Driver_Age'] = sc.fit_transform(xc_train['Driver_Age'].values.reshape(-1, 1))
xc_train['Driving_Exp'] = sc.fit_transform(xc_train['Driving_Exp'].values.reshape(-1, 1))
xc_test['Driver_Age'] = sc.fit_transform(xc_test['Driver_Age'].values.reshape(-1, 1))
xc_test['Driving_Exp'] = sc.fit_transform(xc_test['Driving_Exp'].values.reshape(-1, 1))

# convert to dataframe

xc_train = pd.DataFrame(xc_train)
xc_test = pd.DataFrame(xc_test)


In [28]:
# To build the decision tree model with Under sampling

from sklearn.tree import DecisionTreeClassifier

AutoInsDT_C = DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                                     max_depth=None, max_features=None, max_leaf_nodes=None,
                                     min_impurity_decrease=0.0, min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0,
                                     random_state=None, splitter='best')

AutoInsDT_C = AutoInsDT_C.fit(xc_train,yc_train)

In [29]:
# Predict with test data

yc_pred = AutoInsDT_C.predict(xc_test)

In [30]:
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yc_test

# predicted values 

predicted = yc_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC) 

Confusion matrix : 
 [[20381  3631]
 [ 9703 24301]]
Outcome values : 
 20381 3631 9703 24301
Classification report : 
               precision    recall  f1-score   support

           1       0.68      0.85      0.75     24012
           0       0.87      0.71      0.78     34004

    accuracy                           0.77     58016
   macro avg       0.77      0.78      0.77     58016
weighted avg       0.79      0.77      0.77     58016

Accuracy : 77.0 %
Precision : 67.7 %
Recall : 84.9 %
F1 Score : 0.754
Balanced Accuracy : 78.2 %
MCC : 0.555


In [31]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score3 = AutoInsDT_C.predict_proba(xc_test)[:,1] 
    
false_positive_rate3, true_positive_rate3, threshold3 = roc_curve(yc_test, y_score3) 
    
print('roc_auc_score:', round(roc_auc_score(yc_test, y_score3), 3))

roc_auc_score: 0.782


# Under sampling -Decision tree

In [32]:
# undersampling 

from imblearn.under_sampling import RandomUnderSampler

under = RandomUnderSampler(sampling_strategy = 'majority')
x_under, y_under = under.fit_resample(x, y)

print(x_under.shape)
print(y_under.shape)

(65004, 59)
(65004,)


In [33]:
# To know the count of major and minor classes

y_under.value_counts()

0    32502
1    32502
Name: Policy_Bind, dtype: int64

In [34]:
# Splitting the dataset into train and test

from sklearn.model_selection import train_test_split

xu_train, xu_test, yu_train, yu_test = train_test_split(x_under, y_under, test_size=0.3, random_state=42)

In [35]:
# Feature Scaling - Each independent variable is in different range. The process of transforming all the
# features in the given data set to a fixed range is known as ‘Scaling’

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

xu_train['Driver_Age'] = sc.fit_transform(xu_train['Driver_Age'].values.reshape(-1,1))
xu_train['Driving_Exp'] = sc.fit_transform(xu_train['Driving_Exp'].values.reshape(-1,1))
xu_train['Driver_Age'] = sc.fit_transform(xu_train['Driver_Age'].values.reshape(-1,1))
xu_train['Driving_Exp'] = sc.fit_transform(xu_train['Driving_Exp'].values.reshape(-1,1))

# convert to dataframe

xu_train =  pd.DataFrame(xu_train)
xu_test = pd.DataFrame(xu_test)

In [36]:
# To build the decision tree model with Under sampling

from sklearn.tree import DecisionTreeClassifier

AutoInsDT_C = DecisionTreeClassifier(criterion='gini', splitter='best', max_depth=None, min_samples_split=2, 
                                     min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, 
                                     random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, 
                                     min_impurity_split=None, class_weight=None, ccp_alpha=0.0)

AutoInsDT_C = AutoInsDT_C.fit(xu_train, yu_train)

In [37]:
# Predict with test data

yu_pred = AutoInsDT_C.predict(xu_test)

In [38]:
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yu_test

# predicted values 

predicted = yu_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

Confusion matrix : 
 [[5413 4336]
 [5351 4402]]
Outcome values : 
 5413 4336 5351 4402
Classification report : 
               precision    recall  f1-score   support

           1       0.50      0.56      0.53      9749
           0       0.50      0.45      0.48      9753

    accuracy                           0.50     19502
   macro avg       0.50      0.50      0.50     19502
weighted avg       0.50      0.50      0.50     19502

Accuracy : 50.3 %
Precision : 50.3 %
Recall : 55.5 %
F1 Score : 0.528
Balanced Accuracy : 50.3 %
MCC : 0.007


In [39]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score4 = AutoInsDT_C.predict_proba(xu_test)[:,1] 
    
false_positive_rate4, true_positive_rate4, threshold4 = roc_curve(yu_test, y_score4) 
    
print('roc_auc_score:', round(roc_auc_score(yu_test, y_score4), 3))

roc_auc_score: 0.503


# RANDOM FOREST

# Randomforest with oversampling

In [40]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

AutoInsRF_O = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
criterion='gini', max_depth=None, max_features='auto',
max_leaf_nodes=None, max_samples=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,
min_weight_fraction_leaf=0.0, n_estimators=500,
n_jobs=None, oob_score=False, random_state=0, verbose=0,
warm_start=False)
AutoInsRF_O = AutoInsRF_O.fit(xo_train, yo_train)


# Predict the model with test data set

yo1_pred = AutoInsRF_O.predict(xo_test)
   
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yo_test

# predicted values 

predicted = yo1_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

Confusion matrix : 
 [[31321  2857]
 [  367 33710]]
Outcome values : 
 31321 2857 367 33710
Classification report : 
               precision    recall  f1-score   support

           1       0.99      0.92      0.95     34178
           0       0.92      0.99      0.95     34077

    accuracy                           0.95     68255
   macro avg       0.96      0.95      0.95     68255
weighted avg       0.96      0.95      0.95     68255

Accuracy : 95.3 %
Precision : 98.8 %
Recall : 91.6 %
F1 Score : 0.951
Balanced Accuracy : 95.2 %
MCC : 0.908


In [41]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score5 = AutoInsRF_O.predict_proba(xo_test)[:,1] 
    
false_positive_rate5, true_positive_rate5, threshold5 = roc_curve(yo_test, y_score5) 
    
print('roc_auc_score:', round(roc_auc_score(yo_test, y_score5), 3))

roc_auc_score: 0.958


# RandomForest with Combined Over sampling and Under sampling

In [42]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

AutoInsRF_C = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
criterion='gini', max_depth=None, max_features='auto',
max_leaf_nodes=None, max_samples=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,
min_weight_fraction_leaf=0.0, n_estimators=500,
n_jobs=None, oob_score=False, random_state=0, verbose=0,
warm_start=False)
AutoInsRF_C = AutoInsRF_C.fit(xc_train, yc_train)


# Predict the model with test data set

yc1_pred = AutoInsRF_C.predict(xc_test)

# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yc_test

# predicted values 

predicted = yc1_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

Confusion matrix : 
 [[18905  5107]
 [  139 33865]]
Outcome values : 
 18905 5107 139 33865
Classification report : 
               precision    recall  f1-score   support

           1       0.99      0.79      0.88     24012
           0       0.87      1.00      0.93     34004

    accuracy                           0.91     58016
   macro avg       0.93      0.89      0.90     58016
weighted avg       0.92      0.91      0.91     58016

Accuracy : 91.0 %
Precision : 99.3 %
Recall : 78.7 %
F1 Score : 0.878
Balanced Accuracy : 89.2 %
MCC : 0.822


In [43]:
# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score6 = AutoInsRF_C.predict_proba(xc_test)[:,1] 
    
false_positive_rate6, true_positive_rate6, threshold6 = roc_curve(yc_test, y_score6) 
    
print('roc_auc_score:', round(roc_auc_score(yc_test, y_score6), 3))

roc_auc_score: 0.894


# RandomForest with Under sampling

In [44]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

AutoInsRF_U = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
criterion='gini', max_depth=None, max_features='auto',
max_leaf_nodes=None, max_samples=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,
min_weight_fraction_leaf=0.0, n_estimators=500,
n_jobs=None, oob_score=False, random_state=0, verbose=0,
warm_start=False)
AutoInsRF_U = AutoInsRF_U.fit(xu_train, yu_train)


# Predict the model with test data set

yu1_pred = AutoInsRF_U.predict(xu_test)

# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yu_test

# predicted values 

predicted = yu1_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score7 = AutoInsRF_U.predict_proba(xu_test)[:,1] 
    
false_positive_rate7, true_positive_rate7, threshold7 = roc_curve(yu_test, y_score7) 
    
print('roc_auc_score:', round(roc_auc_score(yu_test, y_score7), 3))

Confusion matrix : 
 [[6542 3207]
 [6524 3229]]
Outcome values : 
 6542 3207 6524 3229
Classification report : 
               precision    recall  f1-score   support

           1       0.50      0.67      0.57      9749
           0       0.50      0.33      0.40      9753

    accuracy                           0.50     19502
   macro avg       0.50      0.50      0.49     19502
weighted avg       0.50      0.50      0.49     19502

Accuracy : 50.1 %
Precision : 50.1 %
Recall : 67.1 %
F1 Score : 0.573
Balanced Accuracy : 50.1 %
MCC : 0.002
roc_auc_score: 0.501


# RandomForest with randam sampling

In [45]:
# Build Random Forest classification model and Train the model using the training sets

from sklearn.ensemble import RandomForestClassifier

AutoInsRF = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
criterion='gini', max_depth=None, max_features='auto',
max_leaf_nodes=None, max_samples=None,
min_impurity_decrease=0.0, min_impurity_split=None,
min_samples_leaf=1, min_samples_split=2,
min_weight_fraction_leaf=0.0, n_estimators=500,
n_jobs=None, oob_score=False, random_state=0, verbose=0,
warm_start=False)
AutoInsRF = AutoInsRF.fit(x_train, y_train)


# Predict the model with test data set
    
y2_pred = AutoInsRF.predict(x_test)
 
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = y_test

# predicted values 

predicted = y2_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score8 = AutoInsRF.predict_proba(x_test)[:,1] 
    
false_positive_rate8, true_positive_rate8, threshold8 = roc_curve(y_test, y_score8) 
    
print('roc_auc_score:', round(roc_auc_score(y_test, y_score8), 3))

Confusion matrix : 
 [[    4  9812]
 [   11 34051]]
Outcome values : 
 4 9812 11 34051
Classification report : 
               precision    recall  f1-score   support

           1       0.27      0.00      0.00      9816
           0       0.78      1.00      0.87     34062

    accuracy                           0.78     43878
   macro avg       0.52      0.50      0.44     43878
weighted avg       0.66      0.78      0.68     43878

Accuracy : 77.6 %
Precision : 26.7 %
Recall : 0.0 %
F1 Score : 0.001
Balanced Accuracy : 50.0 %
MCC : 0.002
roc_auc_score: 0.499


# LOGISTIC REGRESSION

# Oversampling - Logestic regression

In [46]:
# To bulid the 'Logistic Regression' model with oversampling

from sklearn.linear_model import LogisticRegression

AutoInsLR_O = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

AutoInsLR_O = AutoInsLR_O.fit(xo_train,yo_train)

# Predict the model with test data set

yo3_pred = AutoInsLR_O.predict(xo_test)
 
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yo_test

# predicted values 

predicted = yo3_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score9 = AutoInsLR_O.predict_proba(xo_test)[:,1] 
    
false_positive_rate9, true_positive_rate9, threshold9 = roc_curve(yo_test, y_score9) 
    
print('roc_auc_score:', round(roc_auc_score(yo_test, y_score9), 3))

Confusion matrix : 
 [[17938 16240]
 [17553 16524]]
Outcome values : 
 17938 16240 17553 16524
Classification report : 
               precision    recall  f1-score   support

           1       0.51      0.52      0.51     34178
           0       0.50      0.48      0.49     34077

    accuracy                           0.50     68255
   macro avg       0.50      0.50      0.50     68255
weighted avg       0.50      0.50      0.50     68255

Accuracy : 50.5 %
Precision : 50.5 %
Recall : 52.5 %
F1 Score : 0.515
Balanced Accuracy : 50.5 %
MCC : 0.01
roc_auc_score: 0.507


# Combining under - Over sampling Logistic regression

In [47]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

AutoInsLR_C = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)
AutoInsLR_C = AutoInsLR_C.fit(xc_train,yc_train)

# Predict the model with test data set

yc3_pred = AutoInsLR_C.predict(xc_test)

# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yc_test

# predicted values 

predicted = yc3_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC)

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score10 = AutoInsLR_C.predict_proba(xo_test)[:,1] 
    
false_positive_rate10, true_positive_rate10, threshold10 = roc_curve(yo_test, y_score10) 
    
print('roc_auc_score:', round(roc_auc_score(yo_test, y_score10), 3))

Confusion matrix : 
 [[    0 24012]
 [    0 34004]]
Outcome values : 
 0 24012 0 34004
Classification report : 
               precision    recall  f1-score   support

           1       0.00      0.00      0.00     24012
           0       0.59      1.00      0.74     34004

    accuracy                           0.59     58016
   macro avg       0.29      0.50      0.37     58016
weighted avg       0.34      0.59      0.43     58016

Accuracy : 58.6 %
Precision : nan %
Recall : 0.0 %
F1 Score : 0.0
Balanced Accuracy : 50.0 %
MCC : nan
roc_auc_score: 0.508


# Under sampling with Logistic regression

In [48]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

AutoInsLR_U = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

AutoInsLR_U = AutoInsLR_U.fit(xu_train,yu_train)

# Predict the model with test data set

yu3_pred = AutoInsLR_U.predict(xu_test)
   
# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = yu_test

# predicted values 

predicted = yu3_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC) 

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score11 = AutoInsLR_U.predict_proba(xu_test)[:,1] 
    
false_positive_rate11, true_positive_rate11, threshold11 = roc_curve(yu_test, y_score11) 
    
print('roc_auc_score:', round(roc_auc_score(yu_test, y_score11), 3))

Confusion matrix : 
 [[2699 7050]
 [2700 7053]]
Outcome values : 
 2699 7050 2700 7053
Classification report : 
               precision    recall  f1-score   support

           1       0.50      0.28      0.36      9749
           0       0.50      0.72      0.59      9753

    accuracy                           0.50     19502
   macro avg       0.50      0.50      0.47     19502
weighted avg       0.50      0.50      0.47     19502

Accuracy : 50.0 %
Precision : 50.0 %
Recall : 27.7 %
F1 Score : 0.356
Balanced Accuracy : 50.0 %
MCC : 0.0
roc_auc_score: 0.503


# Ramdom sampling with Logistic Regression

In [49]:
# To build the 'Logistic Regression' model with random sampling

from sklearn.linear_model import LogisticRegression

AutoInsLR = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
intercept_scaling=1, max_iter=100, multi_class='auto',
n_jobs=None, penalty='l2', random_state=None,
solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)
AutoInsLR = AutoInsLR.fit(x_train,y_train)

# Predict the model with test data set

y3_pred = AutoInsLR.predict(x_test)

# confusion matrix in sklearn 

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# actual values

actual = y_test

# predicted values 

predicted = y3_pred 

# confusion matrix 

matrix = confusion_matrix(actual,predicted, labels=[1,0],sample_weight=None, normalize=None) 
print('Confusion matrix : \n', matrix) 

# outcome values order in sklearn 

tp, fn, fp, tn = confusion_matrix(actual,predicted,labels=[1,0]).reshape(-1) 

print('Outcome values : \n', tp, fn, fp, tn) 

# classification report for precision, recall f1-score and accuracy 

matrix = classification_report(actual,predicted,labels=[1,0]) 
print('Classification report : \n',matrix) 

# calculating the metrics 

sensitivity = round(tp/(tp+fn), 3) 
specificity = round(tn/(tn+fp), 3); 
accuracy = round((tp+tn)/(tp+fp+tn+fn), 3); 
balanced_accuracy = round((sensitivity+specificity)/2, 3); 
precision = round(tp/(tp+fp), 3); 
f1Score = round((2*tp/(2*tp + fp + fn)), 3);

# Matthews Correlation Coefficient (MCC). Range of values of MCC lie between -1 to +1. 
# A model with a score of +1 is a perfect model and -1 is a poor model 

from math import sqrt 

mx = (tp+fp) * (tp+fn) * (tn+fp) * (tn+fn) 
MCC = round(((tp * tn) - (fp * fn)) / sqrt(mx), 3) 

print('Accuracy :', round(accuracy*100, 2),'%') 
print('Precision :', round(precision*100, 2),'%') 
print('Recall :', round(sensitivity*100,2), '%') 
print('F1 Score :', f1Score) 
print('Balanced Accuracy :', round(balanced_accuracy*100, 2),'%') 
print('MCC :', MCC) 

# Area under ROC curve 
    
from sklearn.metrics import roc_curve, roc_auc_score 
    
y_score12 = AutoInsLR.predict_proba(x_test)[:,1] 
    
false_positive_rate12, true_positive_rate12, threshold12 = roc_curve(y_test, y_score12) 
    
print('roc_auc_score:', round(roc_auc_score(y_test, y_score12), 3))

Confusion matrix : 
 [[    0  9816]
 [    0 34062]]
Outcome values : 
 0 9816 0 34062
Classification report : 
               precision    recall  f1-score   support

           1       0.00      0.00      0.00      9816
           0       0.78      1.00      0.87     34062

    accuracy                           0.78     43878
   macro avg       0.39      0.50      0.44     43878
weighted avg       0.60      0.78      0.68     43878

Accuracy : 77.6 %
Precision : nan %
Recall : 0.0 %
F1 Score : 0.0
Balanced Accuracy : 50.0 %
MCC : nan
roc_auc_score: 0.5
