In [1]:
# Importing the libraries 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

# Ignore harmless warnings 

import warnings 
warnings.filterwarnings("ignore")

import pandasql as psql

# pip install pandasql

In [28]:
# Load the Universal Bank Marketing Campaign (BMC) data

BMCdata = pd.read_csv(r"D:\00 Datasets\Bank\bank-additional-full-V1.0.csv", header=0)
BMCdata.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  Deposit  
0          93.994          -36.4      4.857       5191.0       no  
1          93.994          -36.4      4.857       5191.0       no  
2          93.994          -36.4      4.857       5191.0       no  
3          93.994          -36.4      4.857       5191.0       no  
4          93.994          -36.4      4.857       5191.0       no  

[5 rows x 21 columns]

In [29]:
# displaying the BMC dataset

BMCdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [30]:
# Replace target variable 'Deposit', 'Yes' to 1 and 'No' to 0 and # convert the 'y' to integer value.

BMCdata['Deposit'] = BMCdata['Deposit'].str.replace('yes', '1')
BMCdata['Deposit'] = BMCdata['Deposit'].str.replace('no', '0')
BMCdata['Deposit'] = BMCdata['Deposit'].astype(int)

In [31]:
# Count the target or dependent variable by '0' & '1' and 
# their proportion (> 10 : 1, then the dataset is imbalance dataset)

BMCdata_count = BMCdata.Deposit.value_counts()
print('Class 0:', BMCdata_count[0])
print('Class 1:', BMCdata_count[1])
print('Proportion:', round(BMCdata_count[0] / BMCdata_count[1], 2), ': 1')
print('Total CC Trans:', len(BMCdata))

Class 0: 36548
Class 1: 4640
Proportion: 7.88 : 1
Total CC Trans: 41188


In [32]:
# Dealing with Duplicate values

BMCdata_dup = BMCdata[BMCdata.duplicated(keep='last')]
BMCdata_dup

age          job   marital            education  default housing loan  \
1265    39  blue-collar   married             basic.6y       no      no   no   
12260   36      retired   married              unknown       no      no   no   
14155   27   technician    single  professional.course       no      no   no   
16819   47   technician  divorced          high.school       no     yes   no   
18464   32   technician    single  professional.course       no     yes   no   
20072   55     services   married          high.school  unknown      no   no   
20531   41   technician   married  professional.course       no     yes   no   
25183   39       admin.   married    university.degree       no      no   no   
28476   24     services    single          high.school       no     yes   no   
32505   35       admin.   married    university.degree       no     yes   no   
36950   45       admin.   married    university.degree       no      no   no   
38255   71      retired    single    university.degree       no      no   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
1265   telephone   may         thu  ...         1    999         0   
12260  telephone   jul         thu  ...         1    999         0   
14155   cellular   jul         mon  ...         2    999         0   
16819   cellular   jul         thu  ...         3    999         0   
18464   cellular   jul         thu  ...         1    999         0   
20072   cellular   aug         mon  ...         1    999         0   
20531   cellular   aug         tue  ...         1    999         0   
25183   cellular   nov         tue  ...         2    999         0   
28476   cellular   apr         tue  ...         1    999         0   
32505   cellular   may         fri  ...         4    999         0   
36950   cellular   jul         thu  ...         1    999         0   
38255  telephone   oct         tue  ...         1    999         0   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
1265   nonexistent          1.1          93.994          -36.4      4.855   
12260  nonexistent          1.4          93.918          -42.7      4.966   
14155  nonexistent          1.4          93.918          -42.7      4.962   
16819  nonexistent          1.4          93.918          -42.7      4.962   
18464  nonexistent          1.4          93.918          -42.7      4.968   
20072  nonexistent          1.4          93.444          -36.1      4.965   
20531  nonexistent          1.4          93.444          -36.1      4.966   
25183  nonexistent         -0.1          93.200          -42.0      4.153   
28476  nonexistent         -1.8          93.075          -47.1      1.423   
32505  nonexistent         -1.8          92.893          -46.2      1.313   
36950  nonexistent         -2.9          92.469          -33.6      1.072   
38255  nonexistent         -3.4          92.431          -26.9      0.742   

       nr.employed  Deposit  
1265        5191.0        0  
12260       5228.1        0  
14155       5228.1        0  
16819       5228.1        0  
18464       5228.1        0  
20072       5228.1        0  
20531       5228.1        0  
25183       5195.8        0  
28476       5099.1        0  
32505       5099.1        0  
36950       5076.2        1  
38255       5017.5        0  

[12 rows x 21 columns]

In [33]:
# Remove the identified duplicate records 

BMCdata = BMCdata.drop_duplicates()
BMCdata.shape

(41176, 21)

In [34]:
# Replace target variable 'housing', and convert the 'housing' to integer value.

BMCdata['housing'] = BMCdata['housing'].str.replace('yes', '1')
BMCdata['housing'] = BMCdata['housing'].str.replace('no', '0')
BMCdata['housing'] = BMCdata['housing'].str.replace('unk0wn', '2')
BMCdata['housing'] = BMCdata['housing'].astype(int)

In [35]:
# Replace target variable 'loan', andconvert the 'loan' to integer value.

BMCdata['loan'] = BMCdata['loan'].str.replace('yes', '1')
BMCdata['loan'] = BMCdata['loan'].str.replace('no', '0')
BMCdata['loan'] = BMCdata['loan'].str.replace('unk0wn', '2')
BMCdata['loan'] = BMCdata['loan'].astype(int)

In [36]:
del BMCdata['job']

In [37]:
# Replace the variable 'education', convert the 'education' to integer value.

BMCdata['education'] = BMCdata['education'].str.replace('illiterate', '1')
BMCdata['education'] = BMCdata['education'].str.replace('unknown', '1')
BMCdata['education'] = BMCdata['education'].str.replace('basic.4y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('basic.6y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('basic.9y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('high.school', '3')
BMCdata['education'] = BMCdata['education'].str.replace('professional.course', '4')
BMCdata['education'] = BMCdata['education'].str.replace('university.degree', '5')
BMCdata['education'] = BMCdata['education'].astype(int)

In [38]:
# Replace variable 'marital', and convert the 'marital' to integer value.

BMCdata['marital'] = BMCdata['marital'].str.replace('single', '1')
BMCdata['marital'] = BMCdata['marital'].str.replace('married', '2')
BMCdata['marital'] = BMCdata['marital'].str.replace('divorced', '3')
BMCdata['marital'] = BMCdata['marital'].str.replace('unknown', '4')
BMCdata['marital'] = BMCdata['marital'].astype(int)

In [39]:
# Replace variable 'default', and convert the 'default' to integer value.

BMCdata['default'] = BMCdata['default'].str.replace('yes', '1')
BMCdata['default'] = BMCdata['default'].str.replace('no', '0')
BMCdata['default'] = BMCdata['default'].str.replace('unk0wn', '2')
BMCdata['default'] = BMCdata['default'].astype(int)

In [40]:
# Replace variable 'contact', and convert the 'contact' to integer value.

BMCdata['contact'] = BMCdata['contact'].str.replace('telephone', '1')
BMCdata['contact'] = BMCdata['contact'].str.replace('cellular', '2')
BMCdata['contact'] = BMCdata['contact'].astype(int)

In [41]:
# Replace variable 'day_of_week', and convert the 'day_of_week' to integer value.

BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('mon', '1')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('tue', '2')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('wed', '3')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('thu', '4')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('fri', '5')
BMCdata['day_of_week'] = BMCdata['day_of_week'].astype(int)

In [42]:
# Replace variable 'month', and convert the 'month' to integer value.

BMCdata['month'] = BMCdata['month'].str.replace('mar', '3')
BMCdata['month'] = BMCdata['month'].str.replace('apr', '4')
BMCdata['month'] = BMCdata['month'].str.replace('may', '5')
BMCdata['month'] = BMCdata['month'].str.replace('jun', '6')
BMCdata['month'] = BMCdata['month'].str.replace('jul', '7')
BMCdata['month'] = BMCdata['month'].str.replace('aug', '8')
BMCdata['month'] = BMCdata['month'].str.replace('sep', '9')
BMCdata['month'] = BMCdata['month'].str.replace('oct', '10')
BMCdata['month'] = BMCdata['month'].str.replace('nov', '11')
BMCdata['month'] = BMCdata['month'].str.replace('dec', '12')
BMCdata['month'] = BMCdata['month'].astype(int)

In [43]:
# Replace variable 'poutcome', and convert the 'poutcome' to integer value.

BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('nonexistent', '0')
BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('failure', '1')
BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('success', '2')
BMCdata['poutcome'] = BMCdata['poutcome'].astype(int)

In [44]:
# Identify the independt and dependent variables

from sklearn.model_selection import train_test_split

x = BMCdata.drop('Deposit', axis=1)
y = BMCdata['Deposit'] 

In [51]:
# Splitting the dataset into train and test 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 42,
                                                   stratify=y) 
x_test_f1 = x_test.copy()

In [52]:
# we use Standardization to remove the mean and scale to unit variance

from sklearn.preprocessing import StandardScaler

stdscaler = StandardScaler()

x_train = stdscaler.fit_transform(x_train)
x_train = pd.DataFrame(x_train)

x_test = stdscaler.fit_transform(x_test)
x_test = pd.DataFrame(x_test)

# Linear Kernel

In [53]:
# Training the SVM algorithm for classification problem

from sklearn.svm import SVC

BMCdataSVM = SVC(C=1.0, kernel='linear', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                 probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                 max_iter=- 1, decision_function_shape='ovr', break_ties=False, random_state=42)

BMCdataSVM = BMCdataSVM.fit(x_train, y_train)

In [54]:
# Predictions with test data

y_pred = BMCdataSVM.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y_pred) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y_pred, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y_pred, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y_pred, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred), 3))

[[14316   299]
 [ 1345   511]]
              precision    recall  f1-score   support

           0       0.91      0.98      0.95     14615
           1       0.63      0.28      0.38      1856

    accuracy                           0.90     16471
   macro avg       0.77      0.63      0.66     16471
weighted avg       0.88      0.90      0.88     16471

Accuracy: 90.02 %
Precision: 90.02 %
Recall: 90.02 %
f1-score: 90.02 %
roc_auc_score: 0.627


# Polynomial Kernel

In [49]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMPoly = SVC(kernel='poly', degree=2)
BMCdataSVMPoly.fit(x_train, y_train)

# Predicting the values

y_pred2 = BMCdataSVMPoly.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y_pred2) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y_pred2, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y_pred2, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y_pred2, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred2), 3))

[[14388   192]
 [ 1428   463]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95     14580
           1       0.71      0.24      0.36      1891

    accuracy                           0.90     16471
   macro avg       0.81      0.62      0.66     16471
weighted avg       0.89      0.90      0.88     16471

Accuracy: 90.16 %
Precision: 90.16 %
Recall: 90.16 %
f1-score: 90.16 %
roc_auc_score: 0.616


# Gaussian Kernel

In [50]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMGaussian = SVC(kernel='rbf', random_state = 1, class_weight='balanced')
BMCdataSVMGaussian.fit(x_train, y_train)

# Predicting the values

y_pred3 = BMCdataSVMGaussian.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y_pred3) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y_pred3, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y_pred3, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y_pred3, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred3), 3))

[[12200  2380]
 [  179  1712]]
              precision    recall  f1-score   support

           0       0.99      0.84      0.91     14580
           1       0.42      0.91      0.57      1891

    accuracy                           0.84     16471
   macro avg       0.70      0.87      0.74     16471
weighted avg       0.92      0.84      0.87     16471

Accuracy: 84.46 %
Precision: 84.46 %
Recall: 84.46 %
f1-score: 84.46 %
roc_auc_score: 0.871


# Sigmoid Kernel

In [27]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMSig = SVC(kernel='sigmoid', random_state = 1, class_weight='balanced')
BMCdataSVMSig.fit(x_train, y_train)

# Predicting the values

y_pred4 = BMCdataSVMSig.predict(x_test)

# Confusion matrix and classification report

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

# Evalution metrics

import sklearn.metrics as metrics
from sklearn.metrics import roc_curve, roc_auc_score

print("Accuracy:", (round(metrics.accuracy_score(y_test, y_pred4) * 100, 2)), "%")
print("Precision:", (round(metrics.precision_score(y_test, y_pred4, average='micro') * 100, 2)), '%')
print("Recall:", (round(metrics.recall_score(y_test, y_pred4, average='micro') * 100, 2)), "%")
print("f1-score:", (round(metrics.f1_score(y_test, y_pred4, average='micro') * 100, 2)), '%')
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred4), 3))

[[10693  3887]
 [  498  1393]]
              precision    recall  f1-score   support

           0       0.96      0.73      0.83     14580
           1       0.26      0.74      0.39      1891

    accuracy                           0.73     16471
   macro avg       0.61      0.74      0.61     16471
weighted avg       0.88      0.73      0.78     16471

Accuracy: 73.38 %
Precision: 73.38 %
Recall: 73.38 %
f1-score: 73.38 %
roc_auc_score: 0.735
